# Generated by Django 4.0 on 2022-04-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyIndustry',
            fields=[
                ('year', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='年份')),
                ('primary', models.CharField(max_length=256, verbose_name='第一产业')),
                ('secondary', models.CharField(max_length=256, verbose_name='第二产业')),
                ('tertiary', models.CharField(max_length=256, verbose_name='第三产业')),
                ('animal', models.CharField(max_length=256, verbose_name='农林牧渔业')),
                ('indus', models.CharField(max_length=256, verbose_name='工业')),
                ('construction', models.CharField(max_length=256, verbose_name='建筑业')),
                ('wholesale', models.CharField(max_length=256, verbose_name='批发和零售业')),
                ('transport', models.CharField(max_length=256, verbose_name='交通运输业、仓储邮政业')),
                ('financial', models.CharField(max_length=256, verbose_name='金融业')),
                ('estate', models.CharField(max_length=256, verbose_name='房地产业')),
                ('others', models.CharField(max_length=256, verbose_name='其他')),
                ('total', models.CharField(max_length=256, verbose_name='生产总值')),
            ],
            options={
                'db_table': 'economy_industry',
            },
        ),
        migrations.CreateModel(
            name='EconomyResource',
            fields=[
                ('year', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='年份')),
                ('population', models.CharField(max_length=256, verbose_name='全省年末人口总数 (万人)')),
                ('density', models.CharField(max_length=256, verbose_name='人口密度 (人/平方千米)')),
                ('pLandArea', models.CharField(max_length=256, verbose_name='全省土地面积 (万平方千米)')),
                ('eLandArea', models.CharField(max_length=256, verbose_name='民族自治地方土地面积 (万平方千米)')),
                ('tLandArea', models.CharField(max_length=256, verbose_name='全省年末耕地总资源 (万公顷)')),
                ('pastureArea', models.CharField(max_length=256, verbose_name='牧草地面积 (万公顷)')),
                ('pForestArea', models.CharField(max_length=256, verbose_name='全省森林面积 (万公顷)')),
                ('pForestCoverage', models.CharField(max_length=256, verbose_name='全省森林覆盖率(%)')),
                ('pForestStock', models.CharField(max_length=256, verbose_name='全省森林蓄积量 (亿立方米)')),
                ('pWaterArea', models.CharField(max_length=256, verbose_name='全省水域及水利设施用地面积 (万公顷)')),
                ('pWaterResource', models.CharField(max_length=256, verbose_name='全省水能资源理论蕴藏量 (亿千瓦)')),
                ('pWaterAmount', models.CharField(max_length=256, verbose_name='全省水资源总量 (亿立方米)')),
                ('pOreResource', models.CharField(max_length=256, verbose_name='全省铁矿保有资源储量 (亿吨)')),
                ('pCoalResource', models.CharField(max_length=256, verbose_name='全省煤矿保有资源储量 (亿吨)')),
                ('pPhosphateRes', models.CharField(max_length=256, verbose_name='全省磷矿石保有资源储量 (亿吨)')),
            ],
            options={
                'db_table': 'economy_resource',
            },
        ),
        migrations.CreateModel(
            name='EconomyTotal',
            fields=[
                ('year', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='年份')),
                ('indusAndAgri', models.CharField(max_length=256, verbose_name='工农业总产值  (亿元)')),
                ('agricultural', models.CharField(max_length=256, verbose_name='农业总产值  (亿元)')),
                ('industrial', models.CharField(max_length=256, verbose_name='工业总产值(亿元)')),
                ('lightIndustrial', models.CharField(max_length=256, verbose_name='轻工业产值(亿元)')),
                ('HeavyIndustrial', models.CharField(max_length=256, verbose_name='重工业产值(亿元)')),
                ('AgriAndMachine', models.CharField(max_length=256, verbose_name='农业机械总动力(万千瓦)')),
            ],
            options={
                'db_table': 'economy_total',
            },
        ),
        migrations.CreateModel(
            name='ElectricIndustry',
            fields=[
                ('year', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='年份')),
                ('agr', models.CharField(max_length=256, verbose_name='农、林、牧、渔业')),
                ('industry', models.CharField(max_length=256, verbose_name='工业')),
                ('construction', models.CharField(max_length=256, verbose_name='建筑业')),
                ('trans', models.CharField(max_length=256, verbose_name='交通运输业、仓储邮政业')),
                ('infor', models.CharField(max_length=256, verbose_name='信息传输、计算机服务好软件业')),
                ('comme', models.CharField(max_length=256, verbose_name='商业、住宿餐饮业')),
                ('financial', models.CharField(max_length=256, verbose_name='金融、房地产、商务及居民服务业')),
                ('public', models.CharField(max_length=256, verbose_name='公共事业及管理组织')),
            ],
            options={
                'db_table': 'electric_industry',
            },
        ),
        migrations.CreateModel(
            name='ElectricTotal',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='当前日期')),
                ('total', models.CharField(max_length=256, verbose_name='全社会用电总量')),
                ('predict', models.CharField(max_length=256, verbose_name='预测全社会用电总量')),
                ('prevDate', models.DateTimeField(verbose_name='上个日期')),
            ],
            options={
                'db_table': 'electric_total',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=64, verbose_name='投递日期')),
                ('degree', models.CharField(max_length=16, verbose_name='学历')),
                ('location', models.CharField(max_length=256, verbose_name='所在地')),
                ('industry', models.CharField(max_length=32, verbose_name='行业')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
